### ISSUE TITLE
Instructions on how to install the webapp to the homescreen on iOS and Android need to be written.

### ISSUE THREAD

**Issue by sunderhaus** [sunderhaus/Citizen#4]
There is text in the HTML template on the home page that appear to be placeholders for instructions on how to install the app as an icon on the home screen for [iOS](http://www.tech-recipes.com/rx/44908/ios-add-website-shortcut-to-home-screen/) and for [Android](https://developer.chrome.com/multidevice/android/installtohomescreen). These instructions don't seem to exist. It'd be good information to quickly put together, but I'm not sure on the presentation. Perhaps when the links are tapped/clicked we just show a quick snapshot of the "Share" buttons for iOS, and the equivalent on Android? Thoughts?

**Comment by westown** [comment]
I had hard coded links to 'how to' webpages. Those html links must have been removed.. Here they are...

How to add site to home screen URLs:

Apple device: 
http://www.wikihow.com/Add-a-Link-Button-to-the-Home-Screen-of-an-iPhone

Android device:
http://www.wikihow.com/Set-a-Bookmark-Shortcut-in-Your-Home-Screen-on-Android
